rescue_mission/config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rescue_mission/app/models/answer.rb
class Answer < ApplicationRecord
  # belongs_to :question
  has_many :answer_questions
  has_many :questions, through: :answer_questions
  validates :answer, presence: true, length: {minimum: 50}
end

rescue_mission/app/models/answer_question.rb
class Answer_Question < ApplicationRecord
  belongs_to :answer
  belongs_to :question
end

rescue_mission/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rescue_mission/app/models/question.rb
class Question < ApplicationRecord
  has_many :answer_questions
  has_many :answers, through: :answer_questions
  validates :title, presence: true, length: {minimum: 20}
  validates :description, presence: true, length: {minimum: 50}
end

rescue_mission/app/controllers/answers_controller.rb
require 'pry'
class AnswersController < ApplicationController

  def index
    @answers = Answer.all
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  # => #<ActiveModel::Errors:0x007fe175f1eb50
  #  @base=#<Answer:0x007fe178be8460 id: nil, answer: "dasfasd", created_at: nil, updated_at: nil>,
  #  @details={:question=>[{:error=>:blank}]},
  #  @messages={:question=>["must exist"]}>
  # [5] pry(#<AnswersController>)> @details
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to question_path(@question), notice: 'Answer was successfully created.'
    else
      notice: "Answer must be at least 50 characters long"
      render :new
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

rescue_mission/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rescue_mission/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]


  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def show
    @answers = Answer.all
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(question_params)

    if @question.save
      redirect_to @question, notice: "Question was successfully updated."
    else
      render :show
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path, notice:  "question deleted"
  end


  private

  def set_question
      @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title,:description)
  end
end

rescue_mission/app/helpers/application_helper.rb
module ApplicationHelper
end

rescue_mission/app/views/answers/new.html.erb
<%= form_for([@question, @answer]) do |f| %>

  <div>
    <%= f.label :answer, class: "new_answer" %>
    <%= f.text_field :answer %>
  </div>

  <%= f.submit "Create new answer" %>
<%end%>

rescue_mission/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rescue_mission/app/views/questions/edit.html.erb
<h1> Edit Question </h1>

<%= form_for(@question) do |f| %>
  <div>
    <%= f.label :title, class: "new_question_title" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, class: "new_question_description" %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit "Update Question" %>

<%end%>

<%= link_to "Delete",
             question_path(@question),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>

rescue_mission/app/views/questions/index.html.erb
<h1> Questions </h1>

<% @questions.each do |q| %>
  <li><%= q.title %><%=  link_to "show", question_path(q) %> </li>
<%end%>

<%= link_to "Submit a Question", new_question_path(@question) %>

rescue_mission/app/views/questions/new.html.erb
<h1> New Question </h1>

<%= form_for(@question) do |f| %>
  <div>
    <%= f.label :title, class: "new_question_title" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, class: "new_question_description" %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit "Create new question" %>
<%end%>

rescue_mission/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <center><strong>Title:</strong>
  <%= @question.title %> <br> </center>

  <br><strong>Description:</strong>
  <li><%= @question.description %></li>
</p>
<br>
<h4> <%=link_to "Edit", edit_question_path(@question)%> </h4>
<%= link_to "Delete",
             question_path(@question),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>

<%= link_to "Submit an Answer:", new_question_answer_path(@question) %>
<br>
<br>
<strong> Answers: </strong>
<% if @answers %>
  <%@answers.each do |a| %>
  <bold><li><%= a.answer %></li></bold>
  <%end%>
<%end%>